---
title: "Final"
author: "Ben Wollack"
date: "2026/06/09"
format:
  pdf:
    toc: true
editor: source
execute:
  message: false
  warning: false
---

# Set Up

The link to the GitHub repo can be found here[https://github.com/benwollack/ENVS-193DS_spring-2026_final].

```{r}
#| label: read-in

# read in packages
library(tidyverse)
library(here)

# read in data
nest <- read_csv(here("data", "nest_data_final.csv"))
```


# Problem 1

## a.

In part 1, my coworker used a generalized linear model. I can tell because the results state a probability between two binary outcomes, the American Avocet using the habit or the American Avocet not using the habitat. This response variable is binary, which necessistates a generalized linear model to look at the relationship between that and the predictor of distance to the water.

In part 2, my coworker used a chi-squared test. I can tell because the results compare two categorical variables, habitat and bird species. Looking at the relationship between two categorical variables and seeing if one has an influence on the other requires using a chi-squared test.

## b.

We found that distance to the water's edge influences how birds utilize microhabitats.

We found a significant relationship between bird species (American Avocet, Forster’s Tern, Black-necked Stilt) and the habitats they are found in (managed pond, non-tidal marsh, salt pond, tidal marsh, or tidal mudflat).

## c.

*Water depth* may influence the probability of microhabitat use. The microhabitats are all aquatic, and that water depth may influence things like the ability for birds to wade and the availabiliy of various food sources. Water depth is a continuous variable which can be measured in a unit such as cm or meters. 

For the sake of data collection, it would be helpful to specify something specific and easily measurable like maximum water depth or average water depth after taking multiple measurements of the microhabitat.

# Problem 2

## a.

## b.

## c.

## d.

## e.

## f.

## g.

## h.

## i.

## j.

## k.

# Problem 3

## a. 

## b.

## c.

## d.

## e.

## f.

## g.

